Feature/epmdj 5901
Drill4J/browser-extension pull request #86
Opened 2021-01-22 11:24 UTC by RomanAchilov

2021-01-22 11:36 UTC, IliaSolovev requested changes

2021-01-22 11:36 UTC, IliaSolovev commented on src/popup-script/pages/connection-page/connection-form/connection-form.tsx
> +      {isLoading}
I can`t understand why it need

2021-01-22 11:36 UTC, IliaSolovev commented on src/popup-script/pages/connection-page/connection-page.tsx
> +      console.log(data);
I think it`s unnecessary

2021-01-23 08:28 UTC, RomanDavlyatshin requested changes

2021-01-23 08:28 UTC, RomanDavlyatshin commented on src/popup-script/pages/logo.tsx
> +  <svg viewBox={viewBox} width={`${width}`} height={`${height}`}>
`<Component { ...props } />`?

2021-01-23 08:28 UTC, RomanDavlyatshin commented on src/popup-script/pages/logo.tsx
> +    {height > 16 ? (
That magic number with two svgs looks odd 😄
Can you explain it, please?

2021-01-23 08:28 UTC, RomanDavlyatshin commented on src/popup-script/pages/main-page/agent-not-found/agent-not-found.tsx
> +      <Instructions>If an agent is installed on this site, try refreshing the page.</Instructions>
`<span className="fs-3 lh-lg text-body">...</span>`

`fs-*` - font size
`lh-*` - line height
`text-body` - text color (more examples include `-primary`, `-danger`, `-success`, etc.)

We could have to tweak some SCSS to get this working but would _really_ cut the amount of mysterious `<WhatIsThatComponent>` cases
I mean:
- in that file its called `<Instructions>`
- in the other file, it might be called `<Description>`
- **Both** of them can contain **the same** .scss in independent files for each page
- Why not just use utility classes that don't hide that similarity, but make it obvious instead?

2021-01-23 08:28 UTC, RomanDavlyatshin commented on src/popup-script/pages/main-page/main-page.module.scss
>      cursor: pointer;
1. I suggest styling links globally (e.g. create `global.scss`, inside we could split it to `typography.scss`, `color.scss`, if necessairy)
2. I believe that the `<a>` tag has a `cursor: pointer` by default

2021-01-23 08:28 UTC, RomanDavlyatshin commented on src/popup-script/pages/main-page/main-page.tsx
> +  const { host = '', status = 'OFFLINE' } = agent || {};
Initializing default status here doesn't seem right to me.
Will talk about it later 😄

2021-01-23 08:28 UTC, RomanDavlyatshin commented on src/popup-script/pages/main-page/main-page.tsx
> +              {status === 'NOT_REGISTERED' && (
Please, use enum instead of plain strings (it's already declared)

2021-01-23 08:28 UTC, RomanDavlyatshin commented on src/popup-script/pages/main-page/main-page.tsx
> +                  . To open
That English bothers me. I will have to check it (please do not resolve the conversation)

2021-01-23 08:28 UTC, RomanDavlyatshin commented on src/popup-script/pages/main-page/main-page.tsx
> +                    browser.storage.local.set({ [host]: { ...hostStorage, isWidgetVisible: true } });
Use local storage utility module (with async calls and `await`)
Apparently, I was just in a hurry and forgot to replace it here 😞

2021-01-23 19:19 UTC, RomanAchilov commented on src/hooks/use-agent-on-active-tab.ts
> +export function useAgentOnActiveTab<T>() {
AdapterInfo

2021-01-23 19:34 UTC, RomanAchilov commented on src/popup-script/pages/connection-page/connection-page.tsx
> +      ) : <ConnectionForm initial={initial} />}
maybe leave it like this for now, but closer to the implementation of the option-page, we'll think about how to do it better? (useInitialValue or Create.Context or mb mb effector)
or just lift the state

2021-01-23 19:39 UTC, RomanAchilov commented on src/popup-script/pages/connection-page/connection-form/connection-form.tsx
> +      <Info>
I agree, I also think it would be better this way. Later, we can think about where to place the connection-form for reuse

2021-01-23 20:05 UTC, RomanAchilov commented on src/popup-script/pages/main-page/main-page.tsx
> +              {status === 'NOT_REGISTERED' && (
ok, I like this approach, I just didn't notice it at first

2021-01-23 20:10 UTC, RomanAchilov commented on src/popup-script/pages/logo.tsx
> +  <svg viewBox={viewBox} width={`${width}`} height={`${height}`}>
Spread attributes can be useful but they also make it easy to pass unnecessary props to components that don’t care about them or to pass invalid HTML attributes to the DOM. We recommend using this syntax sparingly.

2021-01-23 20:10 UTC, RomanAchilov commented on src/popup-script/pages/logo.tsx
> +  <svg viewBox={viewBox} width={`${width}`} height={`${height}`}>
https://reactjs.org/docs/jsx-in-depth.html#spread-attributes

I don't mind doing as you ask

2021-01-23 20:12 UTC, RomanAchilov commented on src/popup-script/pages/logo.tsx
> +    {height > 16 ? (
there are problems with SVG, now it's just a hack, I need to take it out in the Ui-kit and everything will be fine and neat

2021-01-23 20:45 UTC, RomanAchilov commented on src/popup-script/pages/main-page/main-page.tsx
> +              {status === 'NOT_REGISTERED' && (
i have problems with enums

2021-03-17 12:02 UTC, RomanDavlyatshin commented
reason: merged in https://github.com/Drill4J/browser-extension/pull/101

2021-03-17 12:02 UTC, closed without merging