Feature/epmdj 5903
Drill4J/browser-extension pull request #87
Opened 2021-01-24 15:35 UTC by IliaSolovev

2021-01-25 08:18 UTC, RomanDavlyatshin commented on src/utils/copy-to-clipboard.ts
> +export function copyToClipboard(text: string) {
There is an alternative API that allows using the clipboard feature. No need to interact with the document 😃 :
```
    await navigator.clipboard.writeText('somestring');
```

2021-01-25 12:52 UTC, RomanDavlyatshin requested changes

2021-01-25 12:52 UTC, RomanDavlyatshin commented on src/content-script-2/components/agent-is-offline/index.tsx
> +export const AgentIsOffline = agentIsOffline(({ className }: Props) => (
Why create a separate file and component just to display some HTML with no logic?

2021-01-25 12:52 UTC, RomanDavlyatshin commented on src/content-script-2/app.tsx
> +    async function loadConfig() {
I suggest using IIFE (to avoid creating pointless named function declaration)
```
React.useEffect(() => {
  (async function () {
    const { [host]: data } = await browser.storage.local.get(host);
    dispatch(setInitial(data));
  }())
}, []);
```

2021-01-25 12:52 UTC, RomanDavlyatshin commented on src/content-script-2/components/extension-position/index.tsx
> +export const ExtensionPosition = ({
I suggest renaming to "ExtensionPositionIcon"

2021-01-25 12:52 UTC, RomanDavlyatshin commented on src/content-script-2/components/extension-position/index.tsx
> +  width, height, viewBox, onClick, rotate,
It's a very thin wrapper around SVG tag
I suggest allowing to pass props directly (because there are no reasons to hide props in that case).
```
(...props) => (
 <svg {...props} >
  ...
 </svg>
)
```

2021-01-25 12:52 UTC, RomanDavlyatshin commented on src/content-script-2/components/connection-lost/index.tsx
> +export const ConnectionLost = connectionLost(({ className }: Props) => (
The situation is similar to `AgentIsOffline` - do not create a separate file just to display some HTML, that is not reusable, nor contains any sort of logic.

2021-01-25 12:52 UTC, RomanDavlyatshin commented on src/content-script-2/components/index.ts
> +export { ExtensionPosition } from './extension-position';
`AgentIsOffline`, `ConnectionLost`, `ExtensionPosition` are not reusable, why put those into `components` folder?
In case if you need to split up a big file, you can use:
1. Pure function components (in the same file)
2. Separate file in the same folder
```
/src/
--/some-page/
----/index.ts
----/not-generic-nor-reusable-component-1.ts
----/not-generic-nor-reusable-component-2.ts
```

2021-01-25 12:52 UTC, RomanDavlyatshin commented on src/content-script-2/components/spinner/index.tsx
> +    <div />
I'm not sure what's going on here, but that scares me 😨 😄
We'll have to talk about it.

2021-01-25 12:52 UTC, RomanDavlyatshin commented on src/content-script-2/pages/finished-manual-test/finished-manual-test.module.scss
> +  font-size: 14px;
I suggest using font & text size utilities from bootstrap

2021-01-25 12:52 UTC, RomanDavlyatshin commented on src/content-script-2/pages/finished-manual-test/finished-manual-test.module.scss
> +  &__vertical-line {
Fixed height looks dubious 😃 Can't we just do:
```
  width: 1px;
  border-right: 1px solid map-get($monochrome, dark-tint);
```
That should stretch to parent flex container height by default

2021-01-25 12:52 UTC, RomanDavlyatshin commented on src/content-script-2/pages/start-new-manual-test/index.tsx
> +              placeholder={isFormSubmitting ? testName : 'Give this test a name'}
Possibly, unnecessary ternary operator? I mean, when `isFormSubmitting === true` placeholder value won't be visible anyway (because input will have a set value)

2021-01-25 12:52 UTC, RomanDavlyatshin commented on src/content-script-2/pages/start-new-manual-test/index.tsx
> +            <div title={!testName ? 'Enter a test name to start testing' : undefined}>
1. I suggest moving a title to the button, this is more a11y-compliant
2. No need to use ternary operator: just leave that title be 😄
3. Even if we needed that, we could do `testName && 'Enter a test name...'` (I believe that there is never a reason to use a ternary operator with the `undefined` as a second expression)

2021-01-25 12:52 UTC, RomanDavlyatshin commented on src/content-script-2/pages/start-new-manual-test/start-new-manual-test.module.scss
> +  &__input {
I suggest making that input style a generic one. Move that to `components` folder 😃

2021-01-25 12:52 UTC, RomanDavlyatshin commented on src/content.scss
> +  width: 100%;
I suggest using `right: 0;` (just because why not, we already have the `absolute` positioning).
Or, there is a reason not to?

2021-01-25 12:52 UTC, RomanDavlyatshin commented on src/content.scss
> +  width: 100vw;
That looks dubious
I mean, it could overflow narrow `body` and break the layout;
On the other hand, with `width: 100%` it will break itself;
We'll have to think about it.

2021-01-25 13:41 UTC, IliaSolovev commented on src/content-script-2/pages/finished-manual-test/finished-manual-test.module.scss
> +  &__vertical-line {
As I understand it will not work because inside this block nothing

2021-01-25 14:24 UTC, IliaSolovev commented on src/content-script-2/pages/start-new-manual-test/index.tsx
> +            <div title={!testName ? 'Enter a test name to start testing' : undefined}>
1) If we want to move a title to the button, we should update ui-kit. But then we need to update react version on the extension repo
2)I can`t use so condition in this case 
![image](https://user-images.githubusercontent.com/49729985/105718278-204f3f00-5f32-11eb-8c85-55e992dcbe7b.png)

2021-01-25 15:49 UTC, IliaSolovev commented on src/utils/copy-to-clipboard.ts
> +export function copyToClipboard(text: string) {
It doesn`t work for me

2021-01-25 15:54 UTC, IliaSolovev commented on src/bootstrap-imports.scss
> +.bold {
I suggest fix it in the merge commit

2021-01-25 17:03 UTC, RomanDavlyatshin commented on src/content-script-2/pages/finished-manual-test/finished-manual-test.module.scss
> +  &__vertical-line {
Well, it does work, take a look https://jsfiddle.net/davlyatshinra/hgoswub3/3/

2021-01-25 17:11 UTC, RomanDavlyatshin commented on src/content-script-2/pages/start-new-manual-test/index.tsx
> +            <div title={!testName ? 'Enter a test name to start testing' : undefined}>
1. Ok, got it;
2. As I've said in point 2. - there is no need to hide the title, just leave it;
P.S. BUT yeah - I guess you're right! 😃 TS forces you to use the ternary operator.

2021-01-25 17:15 UTC, RomanDavlyatshin commented on src/content.scss
> +  width: 100vw;
Please, do not resolve conversations by default :D
I've said "we'll have to think about it" 😄
And we haven't thought about it (yet)!

2021-01-25 17:28 UTC, RomanDavlyatshin requested changes

2021-01-25 17:28 UTC, RomanDavlyatshin commented on src/content-script-2/components/text-input/index.tsx
> +  className, disabled, onChange, value, placeholder,
`({...props}) =>` and `<input {...props}/>`
Again, it's a simple HTML tag, with no logic whatsoever.
What's the reason to hide its real props? It just makes it harder to use it.
E.g. if I wanted to add inline style, I would have to update that component.

2021-01-25 17:28 UTC, RomanDavlyatshin commented on src/content-script-2/pages/manual-test-in-progress/index.tsx
> +    <div className=" d-flex align-items-center gx-6 position-relative">
typo: do not add spaces before classes

2021-01-25 17:31 UTC, RomanDavlyatshin commented on src/bootstrap-imports.scss
> +  font-family: $regular-font !important;
I suggest creating
```
@each $color in $colors {
  .text-#{$color} {
    color: #{$color};
  }
}
```

2021-01-26 07:21 UTC, IliaSolovev commented on src/bootstrap-imports.scss
> +  font-family: $regular-font !important;
These utility classes already exist, but if you are meane create classes for 'font-family' property, I`ll create it

2021-02-02 12:28 UTC, RomanAchilov commented on src/content-script-2/pages/manual-test-error/index.tsx
> +                setTimeout(() => setCopiedToClipboard(false), 5000);
useEffect(() => {
    const timeout = setTimeout(() => setCopied(false), 5000);
    copied && timeout;
    return () => clearTimeout(timeout);
  }, [copied]);

2021-02-02 12:29 UTC, IliaSolovev commented on src/content-script-2/app.module.scss
> +    margin: 6px 0;
i can`t use bootstrap because this margin does not exist in the design system

2021-02-04 06:39 UTC, IliaSolovev commented on src/content-script-2/app.tsx
> +            <span>Please complete registration in the Admin Panel</span>
As I understand `Admin Panel` should be a link. I remember that we can`t to redirect on the admin page. I leave it simple text?

2021-02-04 06:39 UTC, IliaSolovev commented on src/content-script-2/app.tsx
> +            <span>Please complete registration in the Admin Panel</span>
As I understand `Admin Panel` should be a link. I remember that we can`t to redirect on the admin page. I leave it simple text?

2021-03-17 12:02 UTC, RomanDavlyatshin commented
reason: merged in https://github.com/Drill4J/browser-extension/pull/101

2021-03-17 12:02 UTC, closed without merging